import type { DashboardSummary, Lead } from "@/lib/types";

export const leads: Lead[] = [
  {
    id: "LD-1001",
    name: "Aisha Okafor",
    company: "PrimeNest Realty",
    email: "aisha@primenest.com",
    phone: "+234 803 000 1234",
    status: "qualified",
    value: 18000,
    owner: "Fidelix",
    nextAction: "Send pricing proposal and schedule a demo",
    lastContactAt: "2026-10-01",
    tags: ["real estate", "warm lead"],
  },
  {
    id: "LD-1002",
    name: "Daniel Adebayo",
    company: "Lagos Growth Labs",
    email: "daniel@lagosgrowthlabs.com",
    status: "contacted",
    value: 12000,
    owner: "Sarah",
    nextAction: "Follow up with onboarding questions",
    lastContactAt: "2026-09-28",
    tags: ["saas", "follow-up"],
  },
  {
    id: "LD-1003",
    name: "Ngozi Eze",
    company: "Northline Logistics",
    email: "ngozi@northlinelogistics.ng",
    status: "new",
    value: 22000,
    owner: "Fidelix",
    nextAction: "Confirm business needs and qualify fit",
    lastContactAt: "2026-09-30",
    tags: ["logistics", "inbound"],
  },
  {
    id: "LD-1004",
    name: "Tunde Bello",
    company: "BluePeak Consulting",
    email: "tunde@bluepeak.ng",
    status: "proposal",
    value: 26000,
    owner: "Mariam",
    nextAction: "Review proposal and finalize engagement scope",
    lastContactAt: "2026-09-27",
    tags: ["consulting", "proposal"],
  },
  {
    id: "LD-1005",
    name: "Chika Obi",
    company: "UrbanCare Clinics",
    email: "chika@urbancare.ng",
    status: "won",
    value: 35000,
    owner: "Fidelix",
    nextAction: "Kick off onboarding and migration plan",
    lastContactAt: "2026-09-25",
    tags: ["healthcare", "customer"],
  },
];

export const dashboardSummary: DashboardSummary = {
  totalLeads: 42,
  newLeads: 12,
  qualifiedLeads: 18,
  wonLeads: 6,
  pipelineValue: 184000,
  followUpsDue: 9,
  conversionRate: 31,
  recentActivities: [
    { id: "ACT-1", user: "Fidelix", description: "Updated proposal for PrimeNest Realty", time: "2 hours ago" },
    { id: "ACT-2", user: "Sarah", description: "Sent outreach message to Lagos Growth Labs", time: "5 hours ago" },
    { id: "ACT-3", user: "Mariam", description: "Qualified BluePeak Consulting opportunity", time: "Yesterday" },
  ],
};
